DROP DATABASE IF EXISTS CMSDB;
CREATE DATABASE CMSDB;

USE CMSDB;

CREATE TABLE `User`(
userId INT PRIMARY KEY AUTO_INCREMENT,
userName VARCHAR(45) NOT NULL,
firstName VARCHAR(45) NOT NULL,
lastName VARCHAR(45) NOT NULL,
`password` VARCHAR(100) NOT NULL,
phoneNum CHAR(10) NOT NULL
);

CREATE TABLE `Role`(
roleId INT PRIMARY KEY AUTO_INCREMENT,
roleName VARCHAR(45) NOT NULL
);

CREATE TABLE UserRole(
userId INT NOT NULL,
RoleId  INT NOT NULL,
PRIMARY KEY (userId, RoleId),
FOREIGN KEY (userId) REFERENCES `User` (userId),
FOREIGN KEY(roleId) REFERENCES `Role` (roleId) 
);

CREATE TABLE HashTag(
hashtagId INT PRIMARY KEY AUTO_INCREMENT,
hashtagName VARCHAR(45) NOT NULL
);

CREATE TABLE BlogPost(
blogId INT PRIMARY KEY AUTO_INCREMENT,
title VARCHAR(45) NOT NULL,
static BIT NOT NULL,
blogDate DATE NOT NULL,
expiration DATE,
verified BIT NOT NULL,
blogContent TEXT NOT NULL,
image VARCHAR(45) NOT NULL,
userId INT NOT NULL,
FOREIGN KEY (UserId) REFERENCES `User` (userId)
);

-- ALTER TABLE BlogPost ADD PRIMARY KEY (blogId);

CREATE TABLE BlogTag(
hashtagId INT PRIMARY KEY AUTO_INCREMENT,
blogId INT NOT NULL,
PRIMARY KEY (blogId, hashtagId),
FOREIGN KEY(blogId) REFERENCES BlogPost (blogId),
FOREIGN KEY(hashtagId) REFERENCES HashTag (hashtagId)
);

